version: '3'

services:
  nginx:
    build:
      context: ./
      dockerfile: web.docker
    links:
      - php:php
    restart: always
    ports:
      - "86:80"
    volumes:
      - ./:/var/www
  db:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vote
      MYSQL_USER: vote
      MYSQL_PASSWORD: qwerty
  php:
    build:
      context: ./
      dockerfile: php.docker
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www